application: neoe-blog
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: blog.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /(icon.*\.png)
  static_files: static/32_32/\1
  upload: static/32_32/.*\.png
  
- url: /(.*\.(js|css|png|gif|jpg|ico|xml))
  static_files: static/\1
  upload: static/(.*\.(js|css|png|gif|jpg|xml))
